core/urls.py
from django.urls import path, include
from .views import (
    HomeView, CheckoutView,ItemDetailView, 
    add_to_cart,remove_from_cart,OrderSummaryView,
    remove_single_from_cart, add_to_cartt,
    remove_from_cartt, PaymentView,
    record_payment, payment_success,AddCoupon,RequestRefund,
    initiate_payment, VerifyPaymentView,search,posts_by_category,CustomerSupportView,about,policy

    )



app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('search/', search, name='search'),
    path('about/', about, name='about'),
    path('policy/', policy, name='policy'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-coupon/', AddCoupon.as_view(), name='add-coupon'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('category/<slug:slug>/', posts_by_category, name='posts-by-category'),
    path('add-to-cartt/<slug>/', add_to_cartt, name='add-to-cartt'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-from-cartt/<slug>/', remove_from_cartt, name='remove-from-cartt'),
    path('remove-item-from-cart/<slug>/', remove_single_from_cart, name='remove-single-from-cart'),
    path('initiate-payment/', initiate_payment, name='initiate-payment'),
    path('verify_payment/', VerifyPaymentView.as_view(), name='verify-payment'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment'),
    path('record-payment/',record_payment, name='record-payment'),
    path('payment-success/', payment_success, name='payment-success'),
    path('customer-support/', CustomerSupportView.as_view(), name='customer-support'),

    path('refund-request/', RequestRefund.as_view(), name='refund-request'),



]

cs/urls.py
# chat/urls.py

from django.urls import path
from . import views

app_name = 'cs'
urlpatterns = [
    path('start/', views.start_chat, name='start_chat'),
    path('chats/', views.chat_list, name='chat_list'),
    path('chat/<int:chat_id>/', views.chat_detail, name='chat_detail'),
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    # path('auth/', include('social_django.urls', namespace='social')), 
    path('',include('core.urls', namespace= 'core')),
    path('',include('cs.urls', namespace= 'cs')),

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator 
# Create your models here.
from django.urls import reverse
from storages.backends.s3boto3 import S3Boto3Storage

from django_countries.fields import CountryField
from django.db.models.signals import post_save 


CATEGORY_CHOICES= (
    ('S','SHIRT'),
    ('SW','SportWear'),
    ('OW','OutWear')
)


LABEL_CHOICES= (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)

ADDRESS_CHOICES= (
    ('B','Billing'),
    ('S','Shipping'),
)
TYPE_CHOICES =(
    ('BN','BRAND NEW'),
    ('U','LOCAL USED' ),
    ('UK', 'UK USED'),
)
# class UserProfile(models.Model):
#     user = models.OneToOneField(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
#     one_click_purchasing = models.BooleanField(default=False)

#     def __str__(self):
#         return self.user.username
from django.utils.text import slugify 
class Cats(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)





class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    cats = models.ManyToManyField('Cats',blank=True)

    discount_price = models.FloatField(blank=True,null=True)
    category = models.CharField(choices= CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices= LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description =models.TextField()
    quantity = models.IntegerField(default=1,validators=[MinValueValidator(0)])
    image = models.ImageField(storage=S3Boto3Storage(), upload_to='ecom/',blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    type_phone = models.CharField(choices= TYPE_CHOICES, max_length=19)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug':self.slug
        })
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug':self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug':self.slug
        })
    




class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    item = models.ForeignKey(Item, on_delete= models.CASCADE)
    quantity = models.IntegerField(default=1,validators=[MinValueValidator(0)])
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    

   

    

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    ref_code = models.CharField(max_length=100)
    items = models.ManyToManyField(OrderItem)
    Start_date= models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(null=True, blank=True)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete = models.SET_NULL, blank = True, null = True)
    billing_address = models.ForeignKey('Address',  related_name='billing_address', on_delete = models.SET_NULL, blank = True, null = True)
    payment = models.ForeignKey('Payment', on_delete = models.SET_NULL, blank = True, null = True)
    coupon = models.ForeignKey('Coupon', on_delete = models.SET_NULL, blank = True, null = True)
    being_delivered  = models.BooleanField(default=False)
    recieved  = models.BooleanField(default=False)
    refund_requested  = models.BooleanField(default=False)
    refund_granted  = models.BooleanField(default=False)
    

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount

        return total
    

class BillingAddress (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)

    zip = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.user.username
    






# class Payment(models.Model):
#     stripe_charge_id = models.CharField(max_length=50)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,
#                              on_delete=models.SET_NULL, blank=True, null=True)
#     amount = models.FloatField()
#     timestamp = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.user.username
    

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    email = models.EmailField(blank=True, null=True)  # ✅ Add this line
    ref = models.CharField(max_length=100, blank=True, null=True)  # For Paystack
    verified = models.BooleanField(default=False)  # For Paystack
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']
    

    def __str__(self):
        return self.user.username if self.user else "Anonymous Payment"










class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount= models.FloatField()
    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete =models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"
    

class CustomerSupport(models.Model):
    first_name =models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=300)
    email = models.EmailField()



class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple= False)
    zip = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True, null=True)
    address_type = models.CharField(max_length=1, choices = ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    

    class Meta:
        verbose_name_plural ='Addresses'
    

    



# def userprofile_receiver(sender, instance, created, *args, **kwargs):
#     if created:
#         userprofile = UserProfile.objects.create(user=instance)


# post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)




# models.py
# class Payment(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
#     amount = models.FloatField()
#     ref = models.CharField(max_length=100)
#     verified = models.BooleanField(default=False)
#     date = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"{self.user.username} - {self.amount} - {self.ref}"

templates/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Phone {% block head_title %}{% endblock %}</title>
            <script src="https://cdn.tailwindcss.com"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block extra_head %}
    {% endblock %}
    <!-- <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}"> -->
    <!-- <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}"> -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/logos.jpg' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/logos.jpg' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            
                                <img class="img-fluid" src="{% static 'images/logos.jpg' %}" style="max-width: 150px;"/>
                            </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'account_logout' %}"><span><i class="fas fa-user"></i> logout</span></a>

                                        <a href="{% url 'core:order-summary' %}"><span><i class="fas fa-shopping-cart"></i></span>
                                            <span class="count">{{ request.user|cart_item_count }}</span>

                                        </a>
                                        {% if request.user.is_staff %}
                                            <a href="{% url 'cs:chat_list' %}"><span><i class="fas fa-user"></i> chats</span></a>
                                        {% else %}
                                           <a href="{% url 'cs:start_chat' %}"><span><i class="fas fa-user"></i> chat</span></a>
                                        {% endif %}



                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"></i> log in</span></a>
                                                <a href="{% url 'account_signup' %}"><span><i
                                                        class="fas fa-sign-in-alt"></i> sign up</span></a>
                                    {% endif %}
                                </li>
                                <li>
                                  
                                </li>
                             
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

  

</div>

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

{% block extra_body %}
{% endblock %}

{% include "footer.html" %}


{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">    
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->

      <!-- Collapsible wrapper -->
      
      <!-- Right elements -->
      <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="nav-link me-3" href="{% url 'core:order-summary' %}">
          <i class="fas fa-shopping-cart"></i>
          <span class="badge rounded-pill badge-notification bg-danger"></span>
        </a>
  
        <a class="nav-link me-3" href="#">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a class="nav-link me-3" href="#">
          <i class="fab fa-twitter"></i>
        </a>
      </div>
      <!-- Right elements -->
      
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
  
  <!-- carousel -->

  
   <!--Main layout-->
  <main>
  <div class="container">
    <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
    <!-- Container wrapper -->
    <div class="container-fluid">
  
      <!-- Navbar brand -->
      <a class="nav-link text-white" >Brands:</a>
  
      <!-- Toggle button -->
      <button 
         class="navbar-toggler" 
         type="button" 
         data-mdb-toggle="collapse" 
         data-mdb-target="#navbarSupportedContent2" 
         aria-controls="navbarSupportedContent2" 
         aria-expanded="false" 
         aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent2">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
  
          <!-- Link -->
          <li class="nav-item acitve">
            <a class="nav-link text-white">All</a>
          </li>
          {% for cat in cats %}
          <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'core:posts-by-category' slug=cat.slug %}">{{ cat }}</a>
              </li>
              {% endfor %}
  
        </ul>
  
        <!-- Search -->
        <form action="{% url 'core:search' %}" class="w-auto py-1" style="max-width: 12rem">
          <input name="q" type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
  
      </div>
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
    
  <!-- Products -->
    <section>
    <div class="text-center">
      <div class="row">
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
              data-mdb-ripple-color="light">
              <a href="{{ item.get_absolute_url }}">
              {% if item.image %}
                <img src="{{ item.image.url }}" class="w-100">
              {% endif %}
                <div class="mask">
                  <div class="d-flex justify-content-start align-items-end h-100">
                    <h5><span class="badge bg-dark ms-2 {{ item.get_label_display }}">{{ item.get_type_phone_display}}</span></h5>
                  </div>
                </div>
                <div class="hover-overlay">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0);"></div>
                </div>
              </a>
            </div>
            <div class="card-body">
              <a href="{{ item.get_absolute_url }}" class="text-reset">
                <h5 class="card-title mb-2">{{ item.title }}</h5>
              </a>
              {% for cat in item.cats.all %}
              <a href="{{ item.get_absolute_url }}" class="text-reset ">
                <p>{{ cat }}</p>
              </a>
              {% endfor %}
              <h6 class="mb-3 price">$
                {% if item.discount_price %}
                  {{ item.discount_price }}
                {% else %}
                {{ item.price }}
                {% endif %}
              </h6>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  
    </div>
  </section>
    
  <!-- Pagination -->
  {% if is_paginated %}
    <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      <!-- <li class="page-item active"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">4</a></li>
      <li class="page-item"><a class="page-link" href="#">5</a></li> -->

      {% for num in paginator.page_range %}
        {% if num == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endif %}
        {% endfor %}






      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>  
  {% endif %}
  <!-- Pagination -->  
  </div>
  </main>
   <!--Main layout-->
  




{% endblock %}

templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Shop</a></li>
            <li><a href="{% url 'core:customer-support' %}">Customer support</a></li>
            <li><a href="{% url 'core:about' %}">About us</a></li>
            <li><a href="{% url 'core:policy' %}">Policy</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'core:refund-request' %}">Refund Form</a></li>
            {% endif %}
            {% if request.user.is_staff %}
                <li><a href="{% url 'core:refund-request' %}">staff</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge rounded-pill badge-primary">{{ oreder.item.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3">
      {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code}}</small>
            </div>
            <span class="text-success">-${{ order.coupon.amount}}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total}}</strong>
        </li>
        {% endif %}
    </ul>
    <!-- Cart -->
{% if DISPLAY_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
{{ couponform.code }}
<button class="btn btn-primary" type="submit" id="button-addon2" data-mdb-ripple-color="dark">
redeem
</button>
</div>
    </form>
    {% endif %}
</div>

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}

<!-- Navbar -->

  <!-- Navbar -->
  
  <!-- carousel -->

  
   <!--Main layout-->
  <main>
  <div class="container">
    <h2>Order summary </h2>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item title </th>
            <th scope="col">price</th>
            <th scope="col">quantity</th>
            <th scope="col">Total item price</th>
          </tr>
        </thead>
        <tbody>
            {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>

            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-from-cart'  order_item.item.slug %}">
                    <i class="fas fa-minus mr-2"></i>
                </a>{{ order_item.quantity }}
                <a href="{% url 'core:add-to-cartt' order_item.item.slug %}">
                    <i class="fas fa-plus ml-2"></i>
                </a></td>
            <td>
                {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary"> saving ${{ order_item.get_amount_saved }}</span>
                {% else %}
                ${{ order_item.get_total_item_price}}
                {% endif %}
                <a  style="color: red" href="{% url 'core:remove-from-cartt'  order_item.item.slug %}"><i class="fas fa-trash  float-right"></i></a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5"> your cart is empty </td> 

                
            </td>
          </tr>
          <tr colspan="5">
            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
          </tr>
         
          {% endfor %}
          {% if object.coupon %}
          <tr>
            <td colspan="4"><b>coupon</b></td>
            <td> <b>-${{ object.coupon.amount }}</b></td>
          </tr>
          {% endif %}
          {% if object.get_total %}
          <tr>
            <td colspan="4"><b>order total</b></td>
            <td> <b>{{ object.get_total }}</b></td>
          </tr>
          <tr>
            <td colspan="5">
                <a class="btn btn-warning float-right ml-2" href="/checkout/">proceed to checkout</a>
                <a class="btn btn-primary float-right" href="/">Continue shopping</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
  </div>
  </main>
   <!--Main layout-->
  
 



{% endblock %}

templates/refund_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Navbar -->

  <!-- Navbar -->
  
  <!-- carousel -->

  
   <!--Main layout-->
  <main>
  <div class="container">
    <h2>refund form</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  </main>
   <!--Main layout-->
  
 



{% endblock %}